spring:
  datasource:
    url: jdbc:h2:file:/src/main/resources/db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;NON_KEYWORDS=VALUE
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
springdoc:
  api-docs:
    path: /questionSearch/api
  swagger-ui:
    path: /swagger
