spring:
  datasource:
    url: jdbc:mysql://localhost:3306/question_search
    username: root
    password: 12345dsh
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /questionSearch/api
  swagger-ui:
    path: /swagger
